# Generated by Django 2.2.2 on 2020-08-27 12:39

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(upload_to=news.models.upload_location)),
                ('date', models.CharField(blank=True, default='date', max_length=50, null=True)),
                ('time', models.CharField(blank=True, default='time', max_length=50, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
