# Generated by Django 2.2.2 on 2020-08-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='date',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='time',
        ),
    ]
